# Generated by Django 2.2 on 2022-12-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('RAM', models.CharField(max_length=20)),
                ('SSD', models.CharField(max_length=20)),
                ('HDD', models.CharField(max_length=20)),
                ('Processer', models.CharField(max_length=20)),
                ('Colour', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
            ],
        ),
    ]
