# Generated by Django 2.2 on 2022-12-22 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapisco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='discription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_disctiption', models.TextField()),
                ('display_size', models.CharField(max_length=10)),
                ('keyboard_type', models.CharField(max_length=20)),
                ('warrenty', models.CharField(max_length=50)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapisco.LaptopData', unique=True)),
            ],
        ),
    ]
