# Generated by Django 2.2 on 2022-12-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapisco', '0003_auto_20221223_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
