# Generated by Django 2.2 on 2022-12-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapisco', '0004_auto_20221223_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discription',
            old_name='p_disctiption',
            new_name='p_discription',
        ),
        migrations.AlterField(
            model_name='discription',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapisco.LaptopData'),
        ),
    ]
